version: '3.6'
services:
  elasticsearch:
    image: elasticsearch:8.8.0
    container_name: elasticsearch
    environment:
      cluster.name: "my-elk-docker-cluster"
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
      xpack.security.enabled: 'false'
    ports:
    - '9200:9200'
    - '9300:9300'
    networks:
      - ELK

  logstash:
    image: logstash:8.8.0
    container_name: logstash
    build: ./logstash
    depends_on:
     - elasticsearch
    ports:
     - '5140:5140'
     - '5044:5044'
     - '9600:9600'
    networks:
     - ELK

  kibana:
    image: kibana:8.8.0
    container_name: kibana
    ports:
    - '5601:5601'
    depends_on:
      - elasticsearch
    networks:
      - ELK

  nginx:
    image: nginx
    container_name: nginx
    ports:
     - '8000:8000'
    build: ./nginx
    networks:
     - ELK
    depends_on:
     - logstash
    user: $UID

networks:
  ELK:
    driver: bridge
